src/live-quiz/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('', include('quizapp.urls')),
    path('admin/', admin.site.urls),
]

src/quizapp/urls.py
from django.views.generic import RedirectView
from django.urls import path, include
from django.conf.urls import url

from . import views

app_name = 'quizapp'

urlpatterns = [
    path('', views.index, name='index'),
    path('joinquiz/', views.joinQuiz, name='joinQuiz'),
    path('createaccount/', views.createAccount, name='createAccount'),
    path('accounts/profile/', views.profile, name='profile'),
    path('accounts/createQuiz/', views.createQuiz, name='createQuiz'),
    path('accounts/deleteQuiz/', views.deleteQuiz, name='deleteQuiz'),
    path('accounts/deleteQuestion/', views.deleteQuestion, name='deleteQuestion'),
    path('accounts/deleteAnswer/', views.deleteAnswer, name='deleteAnswer'),
    path('accounts/editQuiz/quiz-<int:quizID>/', views.editQuiz, name = 'editQuiz'),
    path('accounts/editQuestion/quiz-<int:quizID>/question-<int:questionID>/', views.editQuestion, name = 'editQuestion'),
    path('accounts/editAnswer/quiz-<int:quizID>/question-<int:questionID>/answer-<int:answerID>/', views.editAnswer, name = 'editAnswer'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('startquiz/quiz-<int:quizID>/', views.startQuiz, name='startQuiz'),
    path('joinquiz/<room_name>/', views.roomJoin, name="roomJoin"),
    path('favicon.ico', RedirectView.as_view(url='/static/quizapp/images/favicon.png')),
    path('hostquiz/<room_name>/', views.teacherView , name='roomMain'),
]

src/quizapp/forms.py
from django import forms


class CreateQuizForm(forms.Form):
    quizName = forms.CharField(
        widget = forms.TextInput(
            attrs = {
                'size': '35',
            }
        ),
        label = "Quiz Name", 
        max_length = 60,
        help_text = "Please enter you quizzes name.")
    quizDescription = forms.CharField(
        #widget=forms.TextInput(attrs={'size': '40'}),
        widget=forms.Textarea(
            attrs = {
                'rows': '10',
                'cols': '40', 
                'style': 'resize: none'
                }),
        label = "Quiz Description", 
        help_text = "Please decribe what this quiz is about.")

class CreateAnswerForm(forms.Form):

    answerText = forms.CharField(
        widget = forms.TextInput(attrs = {'size': '40'}),
        label = "Answer",
        max_length = 50,
        help_text = "Must be less than 25 characters."
    )
    isCorrect = forms.BooleanField(
        widget = forms.CheckboxInput(),
        label = "Correct Answer",    
        required = False,
    )
    pointValue = forms.IntegerField(
        initial=0,
        label = "Answer Value",
    )

class JoinQuizForm(forms.Form):
    sessionId = forms.CharField(
        widget = forms.TextInput(attrs={'class': 'session-id', 'size': '10'}),
        label = 'Enter a quiz ID to join a quiz:',
        max_length = 6
    )

src/quizapp/views.py
from django.urls import reverse
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from django.utils.safestring import mark_safe
from .models import Session, Question
import json

from .forms import CreateQuizForm, CreateAnswerForm, JoinQuizForm
from .models import Quiz    
# Create your views here.

def index(request):
    return render(request, 'quizapp/index.html')

def joinQuiz(request):
    if request.method == 'POST':
        form = JoinQuizForm(request.POST)
        if form.is_valid():
            sessionId = form.cleaned_data.get('sessionId')
            sessionIdUpper = sessionId.upper()
            if Session.objects.filter(_sessionID=sessionIdUpper).exists():
                return redirect(reverse('quizapp:roomJoin', kwargs={'room_name': sessionIdUpper}))
            
    
    form = JoinQuizForm()
    return render(request, 'quizapp/joinquiz.html', {'form': form})

def roomJoin(request, room_name):
    session = Session.objects.get(_sessionID=room_name)
    quizName = session.getQuiz().getQuizName()
    if request.session.get('quiz', False):
        data = request.session.get('quiz')
        userName = data['userName']
        roomName = data['roomName']
        if roomName == room_name:
            return render(request, 'quizapp/studentview.html', {'room_name_json': room_name, 'joined': True, 'userName':userName, 'quizName': quizName})
    
    return render(request, 'quizapp/studentview.html', {'room_name_json': room_name, 'joined': False, 'userName': False, 'quizName': quizName})


def teacherView(request, room_name):
    session = Session.objects.get(_sessionID=room_name)
    quizName = session.getQuiz().getQuizName()
    return render(request, 'quizapp/teacherview.html', {'quizName': quizName, 'room_name_json': room_name})

#Login View is handled by django, as well as logout, and password vies. you do need to create the html templates for each, but it handles the rest. Django authentication is described here https://docs.djangoproject.com/en/2.1/topics/auth/default/

#login_required tells django to look for user authentication in the request, if not it redirects you to the login page.
@login_required
def profile(request):
    user = request.user
    username = user.username
    quizzes = user.quiz_set.all()
    return render(request, 'quizapp/profile.html', {'username': username, 'quizzes': quizzes})

def createAccount(request):
    if request.method == 'GET':
            form = UserCreationForm()

    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect(reverse('quizapp:profile'))
    
    return render(request, 'quizapp/createaccount.html', {'form': form})



@login_required
def deleteQuiz(request):
    if request.method == 'POST':
        quizID = int(request.POST['quizID'])
        quiz = request.user.quiz_set.get(id = quizID)
        quiz.delete()
    return redirect(reverse('quizapp:profile'))

@login_required
def deleteQuestion(request):
    if request.method == 'POST':
        questionID = int(request.POST.get('questionID'))
        quizID = int(request.POST.get('quizID'))
        quiz = request.user.quiz_set.get(id = quizID)
        question = quiz.question_set.get(id = questionID)
        question.delete()
    return redirect(reverse('quizapp:editQuiz', kwargs={'quizID':quiz.id}))

@login_required
def deleteAnswer(request):
    if request.method == 'POST':
        questionID = int(request.POST.get('questionID'))
        quizID = int(request.POST.get('quizID'))
        answerID = int(request.POST.get('answerID'))
        quiz = request.user.quiz_set.get(id = quizID)
        question = quiz.question_set.get(id = questionID)
        answer = question.answer_set.get(id = answerID)
        answer.delete()
    return redirect(reverse('quizapp:editQuestion', kwargs={'quizID':quiz.id, 'questionID': questionID}))

@login_required
def createQuiz(request):
    user = request.user
    if request.method == 'POST':
        form = CreateQuizForm(request.POST)
        if form.is_valid():
            quizName = form.cleaned_data.get('quizName')
            quizDes = form.cleaned_data.get('quizDescription')
            quiz = Quiz(_owner = user, _quizName = quizName, _quizDescription = quizDes)
            quiz.save()
            return redirect(reverse('quizapp:editQuiz', kwargs={'quizID':quiz.id}))
    else:
        form = CreateQuizForm()
    username = user.username
    return render(request, 'quizapp/createquiz.html', {'username': username, 'form': form})


@login_required
def editQuiz(request, quizID):
    user = request.user
    quiz = user.quiz_set.get(id = quizID)
    
    if request.method == 'POST':
        if 'quizButton' in request.POST or 'finishButton' in request.POST:
            form = CreateQuizForm(request.POST)
            if form.is_valid():
                quiz.setQuizName(form.cleaned_data.get('quizName'))
                quiz.setQuizDescription(form.cleaned_data.get('quizDescription'))
                quiz.save()
    
        elif 'questionButton' in request.POST:
            if request.POST.get('questionText', False):
                questionText = request.POST['questionText']
                if not questionText.isspace():
                    quiz.question_set.create(_questionText = questionText)

        if 'finishButton' in request.POST:
            return redirect(reverse('quizapp:profile'))
        return redirect(reverse('quizapp:editQuiz', kwargs={'quizID':quiz.id}))
    else:
        form = CreateQuizForm(initial = {'quizName': quiz.getQuizName(), 'quizDescription': quiz.getQuizDescription()})

    questions = quiz.question_set.all()
    return render(request, 'quizapp/editquiz.html', {'username': user.username, 'quiz':quiz, 'questions': questions, 'form': form})

@login_required
def editQuestion(request, quizID, questionID):
    user = request.user
    quiz = user.quiz_set.get(id = quizID)
    question = quiz.question_set.get(id = questionID)
    
    if request.method == 'POST':
        if 'answerButton' in request.POST:
            form = CreateAnswerForm(request.POST)
            if form.is_valid():
                answerText = form.cleaned_data.get('answerText')
                correct = form.cleaned_data.get('isCorrect')
                points = form.cleaned_data.get('pointValue', 0)
                question.answer_set.create(_text = answerText, _correct = correct, _pointValue = points)
        elif 'questionButton' in request.POST or 'finishButton' in request.POST:
            if request.POST.get('questionText', False):
                questionText = request.POST['questionText']
                if not questionText.isspace():
                    question.setQuestionText(questionText)
                    question.save()
                    
        if 'finishButton' in request.POST:
            return redirect(reverse('quizapp:editQuiz', kwargs={'quizID': quiz.id}))
        return redirect(reverse('quizapp:editQuestion', kwargs={'quizID':quiz.id, 'questionID': questionID}))
    else:
        form = CreateAnswerForm()

    answers = question.answer_set.all()
    return render(request, 'quizapp/editquestion.html', {'username': user.username,'quizID':quiz.id, 'question': question, 'answers': answers, 'form': form})

@login_required
def editAnswer(request, quizID, questionID, answerID):
    user = request.user
    quiz = user.quiz_set.get(id = quizID)
    question = quiz.question_set.get(id = questionID)
    answer = question.answer_set.get(id = answerID)
    
    if request.method == 'POST':
        form = CreateAnswerForm(request.POST)
        if form.is_valid():
            answer.setText(form.cleaned_data.get('answerText'))
            answer.setCorrect(form.cleaned_data.get('isCorrect'))
            answer.setPointValue(form.cleaned_data.get('pointValue', 0))
            answer.save()           
        return redirect(reverse('quizapp:editQuestion', kwargs={'quizID':quiz.id, 'questionID': questionID}))
    else:
        form = CreateAnswerForm(initial = {'answerText': answer.getText(), 'isCorrect': answer.isCorrect() , 'pointValue': answer.getPointValue()})

    return render(request, 'quizapp/editanswer.html', {'username': user.username,'quizID':quiz.id, 'questionID': question.id, 'answer': answer, 'form': form})


@login_required
def startQuiz(request, quizID):
    user = request.user
    quiz = user.quiz_set.get(id = quizID)
    session = quiz.session_set.create(_owner = user.id)
    session.clearAnswers()
    sessionID = session.idGen()
    return redirect(reverse('quizapp:roomMain', kwargs={'room_name': sessionID}))

src/quizapp/templates/quizapp/createaccount.html
<!DOCTYPE html>
<html lang=en>

<head>
    <title>Sign Up</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'quizapp/css/style.css' %}">
    <link rel = "stylesheet" href="{% static 'quizapp/css/login.css' %}"/>
</head>
            
<body>

    {% include "quizapp/partials/header.html" %}

    <article class = "boxcenter">

        <h2>Sign up</h2>
        <form method="post">
            {% csrf_token %}
            <section>

                <article>
                    <p>
                        {{ form.username.label_tag }}<br>
                        {{ form.username }}<br>
                        {% for error in form.username.errors %}
                        <div style="color: red">{{ error }}</div>
                        {% endfor %}
                    </p>
                    
                    <p>
                        {{ form.password1.label_tag }}<br>
                        {{ form.password1 }}<br>
                    </p>
                    {% for error in form.password1.errors %}
                    <p style="color: red">{{ error }}</p>
                    {% endfor %}
                    
                    <p>
                        {{ form.password2.label_tag }}<br>
                        {{ form.password2 }}<br>
                    </p>
                    {% for error in form.password2.errors %}
                    <p style="color: red">{{ error }}</p>
                    {% endfor %}
                </article>
                <article style = "text-align: left">
                        <small style="color: black" >{{ form.username.help_text }}</small>
                    <small style="color: black" >{{ form.password1.help_text }}</small>
                </article>
            </section>
            
            <p>
                <button type="submit">Sign up</button>
            </p>
            <p>
                Already have an account? <a href = "{% url 'quizapp:login' %}">Login</a>
            </p>
        </form>
    </article>
    {% include "quizapp/partials/footer.html" %}
</body>


</html>
    

src/quizapp/templates/quizapp/createquiz.html
<!DOCTYPE html>
<html lang=en>
    
<head>
    <title>Create Quiz</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'quizapp/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'quizapp/css/login.css' %}"/>
</head>
<body style = "text-align: center"></body>

    {% include "quizapp/partials/header.html" %}

    <main class = 'boxcenter'>
        <article>
            <form action = "{% url 'quizapp:createQuiz' %}", method = 'post'>
            <section>
                    {% csrf_token %}
                    <article>
                        <p>
                            {{form.quizName.label_tag}}<br>
                            {{form.quizName}}
                        </p>
                        <p>
                            {{form.quizDescription.label_tag}}<br>
                            {{form.quizDescription}}
                        </p>
                    </article>
                    <article>
                            <p>
                                {{form.quizName.help_text}}
                            </p>
                            <p>
                                {{form.quizDescription.help_text}}
                            </p>
                    </article>
                   
                    
                </section>
                <p><button type = "submit"> Create Quiz </button></p>
            </form>
        </article>
    </main>
    {% include "quizapp/partials/footer.html" %}
</body>

</html>

src/quizapp/templates/quizapp/editanswer.html
<!DOCTYPE html>
<html lang=en>
    
<head>
    <title>Edit Answer</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'quizapp/css/style.css' %}">
    <link rel = "stylesheet" href="{% static 'quizapp/css/login.css' %}"/>
</head>
<body style = "text-align: center"></body>

    {% include "quizapp/partials/header.html" %}

    <main>
        <article class = 'boxcenter', id = 'answerList'>
                <p>    
                    <article >
                        <form action = "{% url 'quizapp:editQuestion' quizID questionID %}" style = 'display: inline' id = "editQuestion"> </form>
                        <form id = 'answerForm' action = "{% url 'quizapp:editAnswer' quizID questionID answer.id %}", method ='post'>
                            <section>
                                {% csrf_token %}
                                <article>
                                    <p>
                                        {{form.answerText.label_tag}}<br>
                                        {{form.answerText}}
                                        
                                    </p>
                                    <p>
                                        {{form.isCorrect.label_tag}}
                                        {{form.isCorrect}}
                                    </p>
                                    <p>
                                        {{form.pointValue.label_tag}}
                                        {{form.pointValue}}
                                    </p>
                                </article>
                                <article>
                                    <p>
                                        {{form.answerText.help_text}}
                                    </p>
                                </article>
                            
                            </section>
                            <article>
                                <button type = "submit" name = 'answerButton'> Save</button>
                                <input type = 'submit' value = "Cancel" form = 'editQuestion'>
                            </article>
                        </form>
                    </article>
                </p>
                <hr>
                
        </article>
                    


    </main>
    {% include "quizapp/partials/footer.html" %}
</body>

</html>

src/quizapp/templates/quizapp/editquestion.html
<!DOCTYPE html>
<html lang=en>
    
<head>
    <title>Edit Question</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'quizapp/css/style.css' %}">
    <link rel = "stylesheet" href="{% static 'quizapp/css/login.css' %}"/>
    <script type="text/javascript" src="{% static 'quizapp/scripts/editquestion.js' %}"></script>
</head>
<body style = "text-align: center"></body>

    {% include "quizapp/partials/header.html" %}

    <main>
        <article class = 'box'>
            <form action = "{% url 'quizapp:editQuestion' quizID question.id %}", method = 'post' id = 'questionForm'>
                <p>
                    {% csrf_token %}
                    <label for = ' questionTextID' >Question:</label>            
                    <input type = 'text' id = 'questionTextID', name = 'questionText', value = "{{question.getQuestionText}}">        
                </p>
            
                <p>
                    <button type = 'submit' name = 'questionButton'>Save</button>
                    <button type = 'submit' name = "finishButton">Finish</button>
                </p>
            </form>
        </article>

        <section>

            <article class = 'boxpadded',>
               
                <article >
                    <form id = 'answerForm' action = "{% url 'quizapp:editQuestion' quizID question.id %}", method ='post'>
                                
                                <article>
                                    <p>
                                        Create 
                                        {{form.answerText.label_tag}}<br>
                                        {{form.answerText}}<br>
                                        {{form.answerText.help_text}}
                                        
                                    </p>
                                    <p>
                                        {{form.isCorrect.label_tag}}
                                        {{form.isCorrect}}
                                    </p>
                                    <p>
                                        {{form.pointValue.label_tag}}
                                        {{form.pointValue}}
                                    </p>
                                </article>
                                    
                            <article>
                                <button type = "submit" name = 'answerButton'> Submit</button>
                                <button type = "button" onclick = cancelAdd()>Cancel</button>
                            </article>
                            {% csrf_token %}
                        </form>
                    </article>
                
            </article>



        <article class = 'boxpadded', id = 'answerList' style = 'flex-grow:2; justify-content: flex-start'>

            Answers
            
            {% if answers %}
            {% for answer in answers %}
            <article >
                <article style = "align-items: flex-end">
                    <form action = "{% url 'quizapp:editAnswer' quizID question.id answer.id %}" method = 'get' id = {{answer.id}}></form>

                    <form action = "{% url 'quizapp:deleteAnswer' %}", method = 'post' style = 'display: inline; margin: 10px'>
                        {{answer.getText}}
                        {% csrf_token %}
                        <input type='hidden' value= {{quizID}} name='quizID'>
                        <input type='hidden' value= {{question.id}} name='questionID'>                       <input type='hidden' value= {{answer.id}} name='answerID'>
                        <button type = 'submit'>Delete Answer</button>
                        <input type = 'submit' value = "Edit Answer" form = {{answer.id}}>
                    </form>
                </article>
            </article> 
            {% endfor %}
            {% endif %}
        </article>
                    
        </section>


    </main>
    {% include "quizapp/partials/footer.html" %}
</body>

</html>

src/quizapp/templates/quizapp/editquiz.html
<!DOCTYPE html>
<html lang=en>
    
<head>
    <title>Edit Quiz</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'quizapp/css/style.css' %}">
    <link rel = "stylesheet" href="{% static 'quizapp/css/login.css' %}"/>
    <script type="text/javascript" src="{% static 'quizapp/scripts/editquiz.js' %}"></script>
</head>
<body style = "text-align: center"></body>

    {% include "quizapp/partials/header.html" %}
    
    <main>
        <section>

            <article class = "boxpadded">
                                
                <form id = 'save' action = "{% url 'quizapp:editQuiz' quiz.id %}", method = 'post'>
                    <section>
                        {% csrf_token %}
                        <article>
                            <p>
                                {{form.quizName.label_tag}}<br>
                                {{form.quizName}}
                            </p>
                            <p>
                                {{form.quizDescription.label_tag}}<br>
                                {{form.quizDescription}}
                            </p>
                        </article>
                    </section>
                </form>
                <p>
                    <button type = 'submit' name = 'quizButton' form = 'save'>Save</button>
                    <button type = 'submit' name = 'finishButton' form = 'save'>Finish</button>
                </p>
            </article>
            
            
            
            <article class = "boxpadded", style = 'justify-content: flex-start; flex-grow: 4; overflow-y: scroll; height: 400px;', id = 'questionList' >    
                <form style = 'margin: 10px', id = 'addForm'>
                    <button type = "button" onclick = addQuestion()> Create Question </button>
                </form>
                <form id = 'questionForm' action = "{% url 'quizapp:editQuiz' quiz.id %}", method ='post', style="display:none; padding: 10px">
                    {% csrf_token %}
                    <label for = 'questionTextID' >Question</label>            
                    <input type = 'text' id = 'questionTextID', name = 'questionText'>
                    <button type = "submit" name = 'questionButton'> Submit</button>
                    <button type = "button" onclick = cancelAdd()>Cancel</button>
                </form>
                            
                {% if questions %}
                {% for question in questions %}
                <article style = "align-items: flex-end">
                    <form action = "{% url 'quizapp:editQuestion' quiz.id question.id %}" style = 'display: none' id = {{question.id}}> </form>
                    <form action = "{% url 'quizapp:deleteQuestion' %}", method = 'post' style = 'margin: 10px'>
                            
                        {{question.getQuestionText}}
                        {% csrf_token %}
                        <input type='hidden' value= {{quiz.id}} name='quizID'>
                        <input type='hidden' value= {{question.id}} name='questionID'>
                        <button type = 'submit'>Delete Question</button>                                
                        <input type = 'submit' value = "Edit Question" form = {{question.id}}>                                    
                    </form>
                </article>
                        {% endfor %}
                {% endif %}
            </article>
                           
        </section>
    </main>
    {% include "quizapp/partials/footer.html" %}
</body>
            
</html>

src/quizapp/templates/quizapp/index.html
<!DOCTYPE html>
<html lang=en>
    
<head>
    <title>Live Quiz</title>
    {% load static %}
        <link rel = 'stylesheet', type='text/css', href="{% static 'quizapp/css/style.css' %}"/>
</head>

<body>

	{% include "quizapp/partials/header.html" %}
		
	<section>
		<a class="no-underline" href="{% url 'quizapp:joinQuiz' %}"><article class="box-button">Join Quiz</article></a>
		{% if request.user.is_authenticated %}
			<a class="no-underline" href="{% url 'quizapp:createQuiz' %}"><article class="box-button">Create Quiz</article></a>
		{% endif %}
	</section>
    
	{% include "quizapp/partials/footer.html" %}

</body>

</html>

src/quizapp/templates/quizapp/joinquiz.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Join Quiz</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'quizapp/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'quizapp/css/login.css' %}">
    <link rel="stylesheet" href="{% static 'quizapp/css/joinQuiz.css' %}">
</head>
<body>
    {% include "quizapp/partials/header.html" %}

    <main class="boxcenter">
        <section class="join-quiz-form">
            <form action="{% url 'quizapp:joinQuiz' %}" method="POST">
                {% csrf_token %}
                <section class="session-id-section">
                    {{ form }}
                </section>
                <input id="submitButton" class="submit-btn" type="submit" value="Join">
            </form>
        </section>
    </main>


    {% include "quizapp/partials/footer.html" %}
</body>
</html>

src/quizapp/templates/quizapp/profile.html
<!DOCTYPE html>
<html lang=en>
    
<head>
    <title>Profile</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'quizapp/css/style.css' %}">
    <link rel = "stylesheet" href="{% static 'quizapp/css/login.css' %}"/>
</head>
<body style = "text-align: center">

    {% include "quizapp/partials/header.html" %}

    <p>
        <form action = "{% url 'quizapp:createQuiz' %}" method = 'get'>
            <button type = "submit"> Create Quiz </button>
        </form>
    </p>
    <hr>
    <section id = 'quizlist'>

        {% if quizzes %}
        {% for quiz in quizzes %}

        <article class = 'quizpadded'>

            <p>
                {{quiz.getQuizName}}
            </p>
            
            <p style = 'font-size: 13px'>
                {{quiz.getQuizDescription|truncatechars:120 }}
            </p>
            <section>
                <form action = "{% url 'quizapp:deleteQuiz' %}", method = 'post' style = 'display: inline'>
                    {% csrf_token %}
                    <input type='hidden' value= {{quiz.id}} name='quizID'>
                    <button type = 'submit'>Delete Quiz</button>
                </form>
                <form action = "{% url 'quizapp:editQuiz' quiz.id %}" style = 'display: inline'>
                    <input type = 'submit' value = "Edit Quiz">
                </form>
                <form action = "{% url 'quizapp:startQuiz' quiz.id %}" target="_blank" style = 'display: inline'>
                    <input type = 'submit' value = "Start Quiz">
                </form>                
            </section>
        </article> 
        
        {% endfor %}
        {% endif %}

    </section>

    {% include "quizapp/partials/footer.html" %}

</body>

</html>

src/quizapp/templates/quizapp/studentview.html
<!-- chat/templates/quizapp/sessionjoin.html -->
<!DOCTYPE html>
<html lang=en>
<head>
	<meta charset="utf-8"/>
	<title>{{quizName}}</title>
	{% load staticfiles %}
		<link rel="stylesheet" href="{% static 'quizapp/css/question.css' %}">
		<link rel = 'stylesheet', type='text/css', href="{% static 'quizapp/css/style.css' %}"/>
		<link rel = 'stylesheet', type='text/css', href="{% static 'quizapp/css/login.css' %}"/>
		<link rel = 'stylesheet', type='text/css', href="{% static 'quizapp/css/joinQuiz.css' %}"/>
		<script type="text/javascript" src="{% static 'quizapp/scripts/studentview.js' %}"></script>
</head>
<body>

	{% include "quizapp/partials/header.html" %}
	
	<main id = "main", style = 'text-align: center;'>
	
	</main>
		
	<img id ='waiting' style="display:block; margin-left: auto; margin-right: auto; display: none;" src="{% static 'quizapp/images/giphy.gif' %}"/>
	
	{% include "quizapp/partials/footer.html" %}
</body>
<script>
	connectToSocket('{{room_name_json}}');
</script>
</html>

src/quizapp/templates/quizapp/teacherview.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <link rel="stylesheet" href="{% static 'quizapp/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'quizapp/css/question.css' %}">
    <title>{{quizName}}</title>
</head>
<body>
    {% include "quizapp/partials/header.html" %}
    
    <main></main>
    <div id="overlay-vote-box">
        <img id="points" src="{% static 'quizapp/images/points.png' %}">
    </div>

    <div style = 'position: fixed; font-size: 30px; left: 0px; bottom: 0px;'>
        {{room_name_json}}
    </div>

    {% include "quizapp/partials/footer.html" %}
    <script src="{% static 'quizapp/scripts/teacherview.js' %}"></script>
    <script>
        connectToSocket('{{ room_name_json }}', '{{ quizName }}');
        
    </script>
</body>
</html>